//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attempt8
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassTbl()
        {
            this.Posts = new HashSet<Post>();
            this.StudentClassOTMs = new HashSet<StudentClassOTM>();
            this.TeacherClassOTMs = new HashSet<TeacherClassOTM>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> School_Id { get; set; }
        public string Code { get; set; }
    
        public virtual SchoolTbl SchoolTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClassOTM> StudentClassOTMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherClassOTM> TeacherClassOTMs { get; set; }
    }
}
