//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attempt8
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialResource
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public double Length { get; set; }
        public byte[] Content { get; set; }
        public int TeacherId { get; set; }
        public int id { get; set; }
        public int Classid { get; set; }
    }
}
