//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attempt8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SE_ProjectEntities : DbContext
    {
        public SE_ProjectEntities()
            : base("name=SE_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<ClassTbl> ClassTbls { get; set; }
        public virtual DbSet<MaterialResource> MaterialResources { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<SchoolTbl> SchoolTbls { get; set; }
        public virtual DbSet<StudentClassOTM> StudentClassOTMs { get; set; }
        public virtual DbSet<StudentTbl> StudentTbls { get; set; }
        public virtual DbSet<TeacherClassOTM> TeacherClassOTMs { get; set; }
        public virtual DbSet<TeacherTbl> TeacherTbls { get; set; }
    }
}
