//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attempt8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int id { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public byte[] Picture { get; set; }
        public string email { get; set; }
        public Nullable<int> class_id { get; set; }
    
        public virtual ClassTbl ClassTbl { get; set; }
    }
}
