//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attempt8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int id { get; set; }
        public byte[] ProfilePicture { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string RelationshipStatus { get; set; }
        public string Designation { get; set; }
        public string PersonalInfo { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> NumberOfClassesEnrolled { get; set; }
    }
}
