//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attempt8
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherClassOTM
    {
        public int Id { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
        public Nullable<int> Class_Id { get; set; }
    
        public virtual ClassTbl ClassTbl { get; set; }
        public virtual TeacherTbl TeacherTbl { get; set; }
    }
}
